// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfFiJHuEq0Hlmq9C8Ej1-Y_6ssS5ELWFo',
    appId: '1:833205764016:web:cc9fc8807847e0c3642075',
    messagingSenderId: '833205764016',
    projectId: 'e-learning-15772',
    authDomain: 'e-learning-15772.firebaseapp.com',
    storageBucket: 'e-learning-15772.appspot.com',
    measurementId: 'G-CCPQ1KHQ4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5-kKJZyfZvjeq_bHVHbjMfvLUsofvFBM',
    appId: '1:833205764016:android:6951f3937c46f959642075',
    messagingSenderId: '833205764016',
    projectId: 'e-learning-15772',
    storageBucket: 'e-learning-15772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYj0PClpyRJIX29n6gG4tk-ESY0J_8ctY',
    appId: '1:833205764016:ios:08ecc98b82cbad29642075',
    messagingSenderId: '833205764016',
    projectId: 'e-learning-15772',
    storageBucket: 'e-learning-15772.appspot.com',
    iosClientId: '833205764016-ne2kr7htf0lm2asp2un9a9nrljkl6jrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYj0PClpyRJIX29n6gG4tk-ESY0J_8ctY',
    appId: '1:833205764016:ios:08ecc98b82cbad29642075',
    messagingSenderId: '833205764016',
    projectId: 'e-learning-15772',
    storageBucket: 'e-learning-15772.appspot.com',
    iosClientId: '833205764016-ne2kr7htf0lm2asp2un9a9nrljkl6jrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizz',
  );
}
